function buyUpgrade(key) {
	if (!checkUpgradeEligibility(key)) {
		return false;
	}
	/** Reaching this part means upgrade purchased. */
	/** Change variables */
	const playerUpgradeData = _.get(game.upgrades, key);
	_.set(
		game.upgrades,
		`${key}.level`,
		playerUpgradeData.level.add(new Decimal("1"))
	);
	const upgradeData = getUpgradeData(key, _.get(game.upgrades, key));
	/** Change HTML */
	const jQueryKey = key.replace(".", "\\.");
	// cost
	$(`#upgrade--${jQueryKey}__level`).text(
		playerUpgradeData.level.toString() +
			"/" +
			upgradeData?.maximumLevel.toString() ?? "inf"
	);
	$(`#upgrade--${jQueryKey}__cost`).text(
		`${formatNumber(upgradeData.costs[0].amount)}` +
			" " +
			`${upgradeData.costs[0].currency}`
	);
	$(`#upgrade--${jQueryKey}__effect`).text(
		`${formatNumber(upgradeData.effect)}`
	);
	return true;
}

function getUpgradeData(key, data) {
	if (data == null) {
		data = _.get(game.upgrades, key);
	}

	const UPGRADES = {
		speed: {
			s1: {
				maximumLevel: new Decimal("99999"),
				costs: [
					{
						amount: new Decimal("10").pow(data.level),
						currency: "money",
					},
				],
				effect: new Decimal("1.1").pow(data.level),
				description: `Increases game speed by x1.1 compounding.`,
			},
		},
		particles: {
			p1: {
				maximumLevel: new Decimal("999"),
				costs: [
					{
						amount: new Decimal("10").mul(
							new Decimal("2").pow(data.level)
						),
						currency: "money",
					},
				],
				effect: new Decimal("2").pow(data.level),
				description: `Increases particles earned from converting electricity by x2 compounding.`,
			},
			p2: {
				maximumLevel: new Decimal("999"),
				costs: [
					{
						amount: new Decimal("20").mul(
							new Decimal("2.03").pow(data.level)
						),
						currency: "money",
					},
				],
				effect: new Decimal("1.5").pow(data.level),
				description: `Increases electricity generated by x1.5 compounding.`,
			},
			p3: {
				maximumLevel: new Decimal("1"),
				costs: [
					{
						amount: new Decimal("84000"),
						currency: "money",
					},
				],
				effect: new Decimal(game.currencies.electricity)
					.mul(data.level)
					.pow(0.125)
					.add(1),
				description: `Increase electricity generated based on current electricity amount.`,
			},
			p4: {
				maximumLevel: new Decimal("1"),
				costs: [
					{
						amount: new Decimal("1000000"),
						currency: "money",
					},
				],
				effect: new Decimal(game.currencies.electricity)
					.mul(data.level)
					.pow(0.0875)
					.add(1),
				description: `Increase particles earned from converting electricity based on current electricity amount.`,
			},
			po: {
				maximumLevel: new Decimal("1"),
				costs: [
					{
						amount: new Decimal("1.5e7"),
						currency: "money",
					},
				],
				effect: new Decimal(data.level),
				// This unlocks prestige layer 1: "Overload"
				description: `Unlocks your ability to destroy your particle generator and your currencies.`,
			},
		},
	};

	return _.get(UPGRADES, key);
}

function checkUpgradeEligibility(key) {
	const playerUpgradeData = _.get(game.upgrades, key);
	const upgradeData = getUpgradeData(key, playerUpgradeData);
	/** This part checks whether player already maxed out upgrade. */
	if (playerUpgradeData.level.gte(upgradeData.maximumLevel)) {
		return false;
	}
	/** This part checks whether player has enough currencies to buy the upgrade. */
	if (!checkCurrencyForUpgrade(key)) {
		return false;
	}
	/** If both are ok, deduct the currencies and return true. */
	const costs = upgradeData.costs;
	for (const condition of costs) {
		game.currencies[condition.currency] = game.currencies[
			condition.currency
		].sub(condition.amount);
	}
	return true;
}

function checkCurrencyForUpgrade(key) {
	const playerUpgradeData = _.get(game.upgrades, key);
	const upgradeData = getUpgradeData(key, playerUpgradeData);
	const costs = upgradeData.costs;
	for (const condition of costs) {
		if (game.currencies[condition.currency].lt(condition.amount)) {
			return false;
		}
	}
	return true;
}
